# This file contains dictionaries having key-points as
# number for various models

YOLO_pose_dict = {
    "LEFT_HIP":11,
    "RIGHT_HIP":12,
    "LEFT_KNEE":13,
    "RIGHT_KNEE":14,
    "LEFT_ANKLE":15,
    "RIGHT_ANKLE":16,
    "RIGHT_SHOULDER":6,
    "LEFT_SHOULDER":5,
    "RIGHT_ELBOW":8,
    "LEFT_ELBOW":7,
    "RIGHT_WRIST":10,
    "LEFT_WRIST":9,
    "RIGHT_EAR":4,
    "LEFT_EAR":3,
    "RIGHT_EYE":2,
    "LEFT_EYE":1,
    "NOSE":0
}

MEDIAPIPE_pose_dict = {
    "NOSE" : 0,
    "LEFT_EYE_INNER" : 1,
    "LEFT_EYE" : 2,
    "LEFT_EYE_OUTER" : 3,
    "RIGHT_EYE_INNER" : 4,
    "RIGHT_EYE" : 5,
    "RIGHT_EYE_OUTER" : 6,
    "LEFT_EAR" : 7,
    "RIGHT_EAR" : 8,
    "MOUTH_LEFT" : 9,
    "MOUTH_RIGHT" : 10,
    "LEFT_SHOULDER" : 11,
    "RIGHT_SHOULDER" : 12,
    "LEFT_ELBOW" : 13,
    "RIGHT_ELBOW" : 14,
    "LEFT_WRIST" : 15,
    "RIGHT_WRIST" : 16,
    "LEFT_PINKY" : 17,
    "RIGHT_PINKY" : 18,
    "LEFT_INDEX" : 19,
    "RIGHT_INDEX" : 20,
    "LEFT_THUMB" : 21,
    "RIGHT_THUMB" : 22,
    "LEFT_HIP" : 23,
    "RIGHT_HIP" : 24,
    "LEFT_KNEE" : 25,
    "RIGHT_KNEE" : 26,
    "LEFT_ANKLE" : 27,
    "RIGHT_ANKLE" : 28,
    "LEFT_HEEL" : 29,
    "RIGHT_HEEL" : 30,
    "LEFT_FOOT_INDEX" : 31,
    "RIGHT_FOOT_INDEX" : 32,
}

TRUE_point_dict = {
    3:"LEFT_HIP",
    2:"RIGHT_HIP",
    4:"LEFT_KNEE",
    1:"RIGHT_KNEE",
    5:"LEFT_ANKLE",
    0:"RIGHT_ANKLE",
    12:"RIGHT_SHOULDER",
    13:"LEFT_SHOULDER",
    11:"RIGHT_ELBOW",
    14:"LEFT_ELBOW",
    10:"RIGHT_WRIST",
    15:"LEFT_WRIST",
    9:"HEAD_TOP",
    8:"UPPER_NECK",
    7:"THORAX",
    6:"PELVIS"
}